### ISSUE TITLE
输入验证码界面乱码

### ISSUE THREAD

**Issue by Azureki** [Saint-Theana/RingZux_QQ#1]
<img width="748" alt="image" src="https://user-images.githubusercontent.com/22387028/59146801-49515200-8a25-11e9-8927-99e4f836cc17.png">

**Comment by Azureki** [comment]
还有一个问题。
运行`./run.sh`命令，提示`无法访问 '/xxx/RingZux_QQ/plugin/libs': 没有那个文件或目录`。
但是，确实是有的。

**Comment by Saint-Theana** [comment]
自己创建一个libs，还有乱码说明屏幕太小，你缩小字体或者放大终端窗口试试

**Comment by Saint-Theana** [comment]
不太清楚libs确实存在又无法访问什么情况，你可以看下那个目录的权限正不正常。删除重新创建一下试试

**Comment by Azureki** [comment]
谢谢。没有问题了。
